version: '3'

services:
  terraform:
    image: hashicorp/terraform:0.12.6
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./:/workdir
    working_dir: "/workdir"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - DATADOG_API_KEY
      - DATADOG_APP_KEY
